stages: 
  -compile
  -test
  -deploy

build:
  stage: compile
  image: hmsbackendd:latest
  script:
    - go get -d -v
    - go build -o bin/hmsbackendd-gin-poc -v .

  test:
    stage: test
    image: hmsbackendd:latest
    script: -go test presentation/* .go

# bin/hmsbackendd-echo-poc
  staging:
    stage: deploy
    script: 
    -apt-get update qy
    -apt-get install -y ruby-dev
    -gem install dpl
    -dpt --provider=heroku --app=hmsbackendd-app --api-key=$HEROKU_API_KEY
  environment:
    name: Development
    url : 
  only :
  -ci-cd
